#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6042-webs
    bind *:80
    mode http
    balance roundrobin
    server 6042-web-01 18.212.203.85:80 check
    server 6042-web-02 3.84.225.21:80 5check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
